/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author c14011
 */
public class Forma01 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma01
     */
    public Forma01() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtTratamiento = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtDni = new javax.swing.JTextField();
        cbxDoctor = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        cbxEspecialidad = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnBuscarID = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        txthoracita = new javax.swing.JTextField();
        txtMotivo1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnOrdenarEspecialidad = new javax.swing.JButton();
        btnBusquedaBinaria = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HISTORIA CLINICA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 190, 40));

        btnGrabar.setBackground(new java.awt.Color(0, 0, 0));
        btnGrabar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGrabar.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabar.setText("REGISTRAR");
        jPanel1.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 40));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 204));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 200, 40));

        txtTratamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRATAMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 190, 40));

        txtDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGNOSTICO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        txtDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 190, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDni.setForeground(new java.awt.Color(0, 0, 255));
        txtDni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 40));

        cbxDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DR. CARLOS", "DR. JOSE", "DR. CESAR", " " }));
        cbxDoctor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOCTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        cbxDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDoctorActionPerformed(evt);
            }
        });
        jPanel4.add(cbxDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 200, 40));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "NOMBRE DEL PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 40));

        cbxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEDICINA GENERAL", "PEDIATRA", "GINECOLOGIA" }));
        cbxEspecialidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESPECIALIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        cbxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecialidadActionPerformed(evt);
            }
        });
        jPanel4.add(cbxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, 40));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 190, 40));

        btnBuscarID.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarID.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarID.setText("IDCITA");
        jPanel4.add(btnBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 40));

        btnFecha.setBackground(new java.awt.Color(0, 204, 204));
        btnFecha.setText("FECHA SELECCIONADA");
        btnFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 160, -1));

        txthoracita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.add(txthoracita, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 630, 190));

        txtMotivo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOTIVO DE CONSULTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.add(txtMotivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 290));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1260, 260));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrdenarEspecialidad.setBackground(new java.awt.Color(0, 0, 204));
        btnOrdenarEspecialidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrdenarEspecialidad.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenarEspecialidad.setText("ORDENAR ESPECIALIDAD");
        jPanel2.add(btnOrdenarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 40));

        btnBusquedaBinaria.setBackground(new java.awt.Color(0, 0, 255));
        btnBusquedaBinaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBusquedaBinaria.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaBinaria.setText("BUSQUEDA BINARIA");
        jPanel2.add(btnBusquedaBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 190, 40));

        btnOrdenar.setBackground(new java.awt.Color(0, 0, 204));
        btnOrdenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("BUSCAR PACIENTE");
        jPanel2.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 200, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1260, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDoctorActionPerformed

    private void cbxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspecialidadActionPerformed

    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Forma01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Forma01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Forma01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Forma01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new Forma01().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnBuscarID;
    public javax.swing.JButton btnBusquedaBinaria;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFecha;
    public javax.swing.JButton btnGrabar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JButton btnOrdenarEspecialidad;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbxDoctor;
    public javax.swing.JComboBox<String> cbxEspecialidad;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtDiagnostico;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtMotivo1;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTratamiento;
    public javax.swing.JTextField txthoracita;
    // End of variables declaration//GEN-END:variables
}
