/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Administrador
 */
public class Forma03 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma01
     */
    public Forma03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnBusquedaRecursiva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        btnAgregarFinal = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btntablahash = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnordenarnombres = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHoraCita = new javax.swing.JTextField();
        txtIdCita = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMotivoCita = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdnipaciente = new javax.swing.JTextField();
        btnconsultarpaciente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreDoctor = new javax.swing.JTextField();
        txthoracita = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jespecialidad = new javax.swing.JComboBox<>();
        cbxEstadoCita = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUNCIONALIDADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusquedaRecursiva.setBackground(new java.awt.Color(0, 0, 0));
        btnBusquedaRecursiva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBusquedaRecursiva.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaRecursiva.setText("BUSQUEDA PACIENTE");
        jPanel1.add(btnBusquedaRecursiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ESPECIALIDAD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, 20));

        btnOrdenar.setBackground(new java.awt.Color(0, 0, 0));
        btnOrdenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setText("ORDENAR CITA");
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 170, 40));

        btnAgregarFinal.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarFinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarFinal.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarFinal.setText("REGISTRAR");
        jPanel1.add(btnAgregarFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 40));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 180, 40));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 170, 40));

        btntablahash.setBackground(new java.awt.Color(0, 0, 0));
        btntablahash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntablahash.setForeground(new java.awt.Color(255, 255, 255));
        btntablahash.setText("BUSQUEDA IDCITA");
        btntablahash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntablahashActionPerformed(evt);
            }
        });
        jPanel1.add(btntablahash, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 180, 40));

        btnlimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnlimpiar.setText("LIMPIAR");
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 170, 40));

        btnordenarnombres.setBackground(new java.awt.Color(0, 0, 0));
        btnordenarnombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnordenarnombres.setForeground(new java.awt.Color(255, 255, 255));
        btnordenarnombres.setText("ORDENAR NOMBRES");
        jPanel1.add(btnordenarnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 980, 120));
        jPanel1.getAccessibleContext().setAccessibleName("FUNCIONALIDADES");

        tblDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 980, 200));

        jPanel2.setBackground(new java.awt.Color(211, 211, 211));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("ID CITA:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("HORA CITA :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 90, -1));

        txtHoraCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHoraCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraCitaActionPerformed(evt);
            }
        });
        jPanel2.add(txtHoraCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 130, 40));

        txtIdCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("MOTIVO CITA :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        txtMotivoCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtMotivoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 130, 40));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO DE CITAS MEDICAS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 440, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("NOMBRE :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtNombrePaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("DNI :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtdnipaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdnipaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdnipacienteActionPerformed(evt);
            }
        });
        jPanel4.add(txtdnipaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 40));

        btnconsultarpaciente.setText("PACIENTE ");
        jPanel4.add(btnconsultarpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 190));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL DOCTOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("especialidad:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel5.add(txtNombreDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 22, 140, 40));

        txthoracita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOTIVO DE CONSULTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel5.add(txthoracita, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("NOMBRE:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jespecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 102, 130, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 260, 190));

        cbxEstadoCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACEPTADA", "CANCELADA", "PENDIENTE", " ", " " }));
        cbxEstadoCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbxEstadoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCitaActionPerformed(evt);
            }
        });
        jPanel2.add(cbxEstadoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 140, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("ESTADO DE CITA:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 980, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdnipacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdnipacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdnipacienteActionPerformed

    private void txtHoraCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraCitaActionPerformed

    private void btntablahashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntablahashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntablahashActionPerformed

    private void cbxEstadoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCitaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Forma03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Forma03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Forma03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Forma03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Forma03().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregarFinal;
    public javax.swing.JButton btnBusquedaRecursiva;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JButton btnconsultarpaciente;
    public javax.swing.JButton btnlimpiar;
    public javax.swing.JButton btnordenarnombres;
    public javax.swing.JButton btntablahash;
    public javax.swing.JComboBox<String> cbxEstadoCita;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jespecialidad;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtHoraCita;
    public javax.swing.JTextField txtIdCita;
    public javax.swing.JTextField txtMotivoCita;
    public javax.swing.JTextField txtNombreDoctor;
    public javax.swing.JTextField txtNombrePaciente;
    public javax.swing.JTextField txtdnipaciente;
    public javax.swing.JTextField txthoracita;
    // End of variables declaration//GEN-END:variables
}
