
package Vista;
public class FrmPrincipal extends javax.swing.JFrame {
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        registropacientes = new javax.swing.JMenuItem();
        historiaclinica = new javax.swing.JMenuItem();
        Especialidad = new javax.swing.JMenuItem();
        registrodoctor = new javax.swing.JMenuItem();
        Busquedas = new javax.swing.JMenuItem();
        jcitas = new javax.swing.JMenuItem();
        atenciones = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpnEscritorio.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        jMenu3.setText("POSTA");

        registropacientes.setText("Registro de Paciente");
        registropacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registropacientesActionPerformed(evt);
            }
        });
        jMenu3.add(registropacientes);

        historiaclinica.setText("historiaclinica");
        historiaclinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaclinicaActionPerformed(evt);
            }
        });
        jMenu3.add(historiaclinica);

        Especialidad.setText("Especialidad");
        Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadActionPerformed(evt);
            }
        });
        jMenu3.add(Especialidad);

        registrodoctor.setText("Registro del Doctor");
        registrodoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodoctorActionPerformed(evt);
            }
        });
        jMenu3.add(registrodoctor);

        Busquedas.setText("Busquedas");
        jMenu3.add(Busquedas);

        jcitas.setText("Citas");
        jcitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcitasActionPerformed(evt);
            }
        });
        jMenu3.add(jcitas);

        atenciones.setText("Atencion");
        atenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atencionesActionPerformed(evt);
            }
        });
        jMenu3.add(atenciones);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registropacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registropacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registropacientesActionPerformed

    private void historiaclinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaclinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historiaclinicaActionPerformed

    private void EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadActionPerformed

    private void registrodoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrodoctorActionPerformed

    private void jcitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcitasActionPerformed

    private void atencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atencionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atencionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Busquedas;
    public javax.swing.JMenuItem Especialidad;
    public javax.swing.JMenuItem atenciones;
    public javax.swing.JDesktopPane dpnEscritorio;
    public javax.swing.JMenuItem historiaclinica;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jcitas;
    public javax.swing.JMenuItem registrodoctor;
    public javax.swing.JMenuItem registropacientes;
    // End of variables declaration//GEN-END:variables
}
